version: '3.9'

services:
  # MongoDB services

  mongodb:
    container_name: mongodb
    image: mongo:latest
    restart: always
    ports:
      - 2717:27017
    volumes:
      - mongodb:/data/db

  # Node Api service 
  api:
    build: .
    ports:
      - 3030:3030
    volumes:
      - .:/app
    environment:
      PORT: 3030
      MONGODB_URI: 'mongodb+srv://Isabel:Isabel77@cluster0.ffepb.mongodb.net/myFirstDatabase?retryWrites=true&w=majority'
      DB_NAME: plant_db
      NAME: Isabel
    depends_on:
      - mongo_db

volumes:
  mongodb: {}

# version: "3.7"
# services:
#   mongo:
#     container_name: mongo
#     image: mongo
#     restart: always
#     volumes:
#       - ./data:/data/db
#     ports:
#       - 27017:27017
#   app:
#     container_name: app
#     restart: always
#     build:
#       context: .
#       dockerfile: Dockerfile.dev
#     env_file: .env.local
#     environment:
#       - PORT=3030
#       - MONGO_URL=${MONGO_URL}
#     ports:
#       - 3030:3030
#     external_links:
#       - mongo
#     depends_on:
#       - mongo
# volumes:
#   mongo-data:
#     driver: local
