version: '3.9'

services:
  # MongoDB services

  mongodb:
    container_name: mongodb
    image: mongo:latest
    restart: always
    ports:
      - 2717:27017
    volumes:
      - mongodb:/data/db

  # Node Api service 
  api:
    build: .
    ports:
      - 3030:3030
    volumes:
      - .:/app
    environment:
      PORT: 3030
      MONGODB_URI: 'mongodb+srv://Isabel:Isabel77@cluster0.ffepb.mongodb.net/myFirstDatabase?retryWrites=true&w=majority'
      DB_NAME: plant_db
      NAME: Isabel
    depends_on:
      - mongo_db

volumes:
  mongodb: {}